-- MySQL Script generated by MySQL Workbench
-- Sat Oct  6 18:50:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecoservi_plataforma17
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecoservi_plataforma17
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecoservi_plataforma17` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `ecoservi_plataforma17` ;

-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_activo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_activo` (
  `id_activo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_activo` VARCHAR(50) NOT NULL,
  `estado_activo` INT(11) NULL DEFAULT NULL,
  `id_tipo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_activo`))
ENGINE = MyISAM
AUTO_INCREMENT = 326
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`afp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`afp` (
  `id_afp` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_afp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_afp`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_articulos` (
  `id_articulo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_articulo` TEXT NULL DEFAULT NULL,
  `id_activo` INT(11) NULL,
  `valor_articulo` INT NULL DEFAULT NULL,
  `id_unidad` INT(11) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `cod_barras` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 883
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_detalle_saldotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_detalle_saldotacion` (
  `id_detalle_salidotacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_salida_dotacion` INT(11) NULL DEFAULT NULL,
  `id_activo` INT(11) NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `id_articulo` INT(11) NULL DEFAULT NULL,
  `cantidad_entregada` INT(11) NULL DEFAULT NULL,
  `cantidad_aprobada` INT(11) NULL DEFAULT NULL,
  `cantidad_retornada` INT(11) NULL DEFAULT NULL,
  `codigo_articulo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_detalle_salidotacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 19374
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_detalle_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_detalle_solicitud` (
  `id_detalle_solicitud` INT(11) NOT NULL AUTO_INCREMENT,
  `id_solicitud_producto` INT(11) NULL DEFAULT NULL,
  `id_articulo` INT(11) NULL DEFAULT NULL,
  `cantidad_solicitada` INT(11) NULL DEFAULT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  `id_estado` INT(11) NULL DEFAULT NULL,
  `cantidad_aprobada` INT(11) NULL DEFAULT NULL,
  `observaciones_revision` TEXT NULL DEFAULT NULL,
  `cantidad_entregada` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle_solicitud`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_elementos_dotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_elementos_dotacion` (
  `id_tipo_dotacion` INT(11) NULL DEFAULT NULL,
  `id_activo` INT(11) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `vigencia` INT(11) NULL DEFAULT NULL,
  `tiempo_minimo` INT(11) NULL DEFAULT NULL,
  `segunda` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_inventariocc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_inventariocc` (
  `id_inventarioCC` INT(11) NOT NULL AUTO_INCREMENT,
  `id_articulo` INT(11) NULL DEFAULT NULL,
  `id_destino` INT(11) NULL DEFAULT NULL,
  `cantidad_cc` INT(11) NULL DEFAULT NULL,
  `cantidad_minima` INT(11) NULL DEFAULT NULL,
  `cantidad_maxima` INT(11) NULL DEFAULT NULL,
  `cantidad_preaprobada` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_inventarioCC`))
ENGINE = InnoDB
AUTO_INCREMENT = 267
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_salida_dotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_salida_dotacion` (
  `id_salida_dotacion` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_solicitud` DATE NULL DEFAULT NULL,
  `id_empleado_recibe` INT(11) NULL DEFAULT NULL,
  `recibido_empleado` TEXT NULL DEFAULT NULL,
  `fecha_autorizacion` DATE NULL DEFAULT NULL,
  `id_empleado_autoriza` INT(11) NULL DEFAULT NULL,
  `fecha_entrega` DATE NULL DEFAULT NULL,
  `documento_soporte` TEXT NULL DEFAULT NULL,
  `tipo_entrega` INT(11) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `id_empleado_solicita` INT(11) NULL DEFAULT NULL,
  `id_empleado_entrega` INT(11) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `id_contrato` INT(11) NOT NULL,
  PRIMARY KEY (`id_salida_dotacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 5788
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_solicitud_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_solicitud_producto` (
  `id_solicitud_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_solicitud` DATE NULL DEFAULT NULL,
  `id_empleado_solicita` INT(11) NULL DEFAULT NULL,
  `fecha_revision` DATE NULL DEFAULT NULL,
  `id_empleado_revisa` INT(11) NULL DEFAULT NULL,
  `id_estado` INT(11) NULL DEFAULT NULL,
  `id_empleado_entrega` INT(11) NULL DEFAULT NULL,
  `fecha_entrega` DATE NULL DEFAULT NULL,
  `id_destino` INT(11) NULL DEFAULT NULL,
  `id_origen` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitud_producto`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_solicitud_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_solicitud_servicio` (
  `id_solicitud_servicio` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_solicitud` DATE NULL DEFAULT NULL,
  `id_empleado_solicita` INT(11) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `detalle_servicio` TEXT CHARACTER SET 'latin1' COLLATE 'latin1_spanish_ci' NULL DEFAULT NULL,
  `tiempo` VARCHAR(45) NULL DEFAULT NULL,
  `condiciones` TEXT NULL DEFAULT NULL,
  `id_empleado_aprueba` INT(11) NULL DEFAULT NULL,
  `fecha_aprobacion` DATE NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `observaciones_aprobacion` TEXT NULL DEFAULT NULL,
  `archivo_soporte` TEXT NULL DEFAULT NULL,
  `id_centro_costo` INT(11) NULL DEFAULT NULL,
  `id_orden_servicio` INT(11) NULL DEFAULT NULL,
  `nombre_proveedor` VARCHAR(100) NULL DEFAULT NULL,
  `valor_servicio` INT(11) NULL DEFAULT NULL,
  `fecha_cumplimiento` DATE NULL DEFAULT NULL,
  `observaciones_cumplimiento` TEXT NULL DEFAULT NULL,
  `nit_proveedor` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitud_servicio`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_tipo_dotacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_tipo_dotacion` (
  `id_tipo_dotacion` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion_dotacion` VARCHAR(45) NULL DEFAULT NULL,
  `nombre_dotacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_dotacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`arc_facturase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`arc_facturase` (
  `idFactEgreso` INT(11) NOT NULL AUTO_INCREMENT,
  `idArcEgreso` INT(11) NULL DEFAULT NULL,
  `NumFactura` INT(11) NULL DEFAULT NULL,
  `valorFactura` INT(11) NULL DEFAULT NULL,
  `fechaFact` DATE NULL DEFAULT NULL,
  `fileFactura` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idFactEgreso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`caja_compensacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`caja_compensacion` (
  `id_caja` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_caja` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_caja`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`cargos` (
  `id_cargo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(45) NULL DEFAULT NULL,
  `salario_base` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_categorias` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`centro_costos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`centro_costos` (
  `id_destino` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_destino` VARCHAR(45) NULL DEFAULT NULL,
  `id_estado` INT(11) NULL DEFAULT NULL,
  `id_centro` INT(11) NOT NULL,
  PRIMARY KEY (`id_destino`))
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`centros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`centros` (
  `id_centro` INT(11) NOT NULL,
  `nombre_centro` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_centro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`cesantias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`cesantias` (
  `id_cesantias` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cesantias` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cesantias`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`ci_autoevaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`ci_autoevaluacion` (
  `id_auto` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATE NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `id_crea` INT(11) NOT NULL,
  `id_dependencia` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_auto`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`ci_pregAutoevaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`ci_pregAutoevaluacion` (
  `id_pregauto` INT(11) NOT NULL AUTO_INCREMENT,
  `id_auto` INT(11) NOT NULL,
  `id_pregunta` INT(11) NOT NULL,
  `valores` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `obligatorio` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_pregauto`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`ci_preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`ci_preguntas` (
  `id_pregunta` INT(11) NOT NULL AUTO_INCREMENT,
  `enunciado` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `id_tipopreg` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_pregunta`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`ci_rtaAutoevaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`ci_rtaAutoevaluacion` (
  `id_rta` INT(11) NOT NULL AUTO_INCREMENT,
  `id_pregAuto` INT(11) NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `rta` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `valor` DECIMAL(10,0) NOT NULL,
  `texto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_rta`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`ci_tipopreg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`ci_tipopreg` (
  `id_tipo` INT(11) NOT NULL,
  `valores` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `seleccion` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`clientes` (
  `codigo_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cliente` TINYTEXT NOT NULL,
  `nit_cliente` TINYTEXT NOT NULL,
  `direccion_cliente` TINYTEXT NOT NULL,
  `telefono_cliente` TINYTEXT NOT NULL,
  `correo_cliente` TINYTEXT NOT NULL,
  `id_estado` INT(2) NOT NULL,
  `imagen` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo_cliente`))
ENGINE = MyISAM
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`contratos` (
  `id_contrato` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_cliente` INT(11) NULL DEFAULT NULL,
  `id_destino` INT(11) NULL DEFAULT NULL,
  `numero_contrato` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `id_estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contrato`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`contratos_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`contratos_empleado` (
  `id_contrato` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_empleado` BIGINT(20) NULL DEFAULT NULL,
  `fecha_ingreso` DATE NULL DEFAULT NULL,
  `fecha_vencimiento` DATE NULL DEFAULT NULL,
  `fecha_retiro` DATE NULL DEFAULT NULL,
  `eps` INT(11) NULL DEFAULT NULL,
  `afp` INT(11) NULL DEFAULT NULL,
  `cesantias` INT(11) NULL DEFAULT NULL,
  `caja_compensacion` INT(11) NULL DEFAULT NULL,
  `evaluacionPrueba` DATE NULL DEFAULT NULL,
  `radicadoEps` DATE NULL DEFAULT NULL,
  `radicadoAfp` DATE NULL DEFAULT NULL,
  `radicadoCaja` DATE NULL DEFAULT NULL,
  `centro_trabajo` VARCHAR(60) NULL DEFAULT NULL,
  `motivo_retiro` VARCHAR(45) NULL DEFAULT NULL,
  `id_destino` INT(11) NULL DEFAULT NULL,
  `id_tipo_dotacion` INT(11) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `fecha_examen_ingreso` DATE NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `num_cuenta` VARCHAR(45) NULL DEFAULT NULL,
  `banco` VARCHAR(45) NULL DEFAULT NULL,
  `radicadoCesantias` DATE NOT NULL,
  `id_cargo` INT(20) NOT NULL,
  PRIMARY KEY (`id_contrato`))
ENGINE = InnoDB
AUTO_INCREMENT = 1557
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`dependencia` (
  `id_dependencia` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_dependencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`eco_actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`eco_actividades` (
  `id_actividad` INT(11) NOT NULL AUTO_INCREMENT,
  `id_grupo` INT(11) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(45) NULL DEFAULT NULL,
  `orden` INT NULL,
  PRIMARY KEY (`id_actividad`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`eco_actividades_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`eco_actividades_usuario` (
  `id_actividad_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_actividad` INT(11) NULL DEFAULT NULL,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_actividad_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 1649
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`eco_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`eco_grupos` (
  `id_grupo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `id_modulo` INT(11) NULL DEFAULT NULL,
  `icono_grupo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`eco_modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`eco_modulos` (
  `id_modulo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_modulo` VARCHAR(45) NULL DEFAULT NULL,
  `icono_modulo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`empleado` (
  `id_empleado` BIGINT(20) NOT NULL,
  `nombre_empleado` TINYTEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `apellido_empleado` TINYTEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `direccion_empleado` TINYTEXT CHARACTER SET 'latin1' NOT NULL,
  `telefono_empleado` TINYTEXT CHARACTER SET 'latin1' NOT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `id_estado` BIGINT(20) NOT NULL,
  `fecha_expedicion` DATE NULL DEFAULT NULL,
  `lugar_expedicion` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `grupo_sanguineo` VARCHAR(4) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `genero` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `num_hijos` INT(11) NULL DEFAULT NULL,
  `escolaridad` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `tel_contacto` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `nom_contacto` VARCHAR(45) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `talla_botas` VARCHAR(4) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `talla_overol` VARCHAR(4) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `talla_impermeable` VARCHAR(4) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `observaciones` TEXT CHARACTER SET 'latin1' NULL DEFAULT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`eps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`eps` (
  `id_eps` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_eps` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_eps`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`estados` (
  `id_estados` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estados`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`eventos_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`eventos_app` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `info` VARCHAR(70) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `nombres_usuario` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `apellidos_usuario` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `id_usuario` INT(11) NOT NULL,
  `id_tipo_usuario` INT(11) NOT NULL,
  `version_app` INT(11) NOT NULL,
  `detalles` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 522
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`planeador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`planeador` (
  `id_tarea` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  `tipo_tarea` INT(11) NULL DEFAULT NULL,
  `dia_inicio` INT(11) NULL DEFAULT NULL,
  `dias` INT(11) NULL DEFAULT NULL,
  `texto` TEXT NULL DEFAULT NULL,
  `documentos` TEXT NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `periodo` INT(11) NULL DEFAULT NULL,
  `mes_programacion` INT(11) NULL DEFAULT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id_tarea`))
ENGINE = InnoDB
AUTO_INCREMENT = 342
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`registro_fotografico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`registro_fotografico` (
  `id_programacion` INT(11) NOT NULL,
  `imagenes` VARCHAR(1000) CHARACTER SET 'utf8' NOT NULL,
  `tipo_registro` INT(11) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`th_extras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`th_extras` (
  `id_extra` INT(11) NOT NULL AUTO_INCREMENT,
  `id_contrato` INT(11) NULL DEFAULT NULL,
  `id_empleado_reporta` BIGINT(20) NULL DEFAULT NULL,
  `hed` FLOAT NULL DEFAULT NULL,
  `rdf` FLOAT NULL DEFAULT NULL,
  `hefd` FLOAT NULL DEFAULT NULL,
  `hen` FLOAT NULL DEFAULT NULL,
  `rn` FLOAT NULL DEFAULT NULL,
  `rnf` FLOAT NULL DEFAULT NULL,
  `henf` FLOAT NULL DEFAULT NULL,
  `base` BIGINT(20) NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  `mes_reporte` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_extra`))
ENGINE = InnoDB
AUTO_INCREMENT = 2015
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`th_extrasxls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`th_extrasxls` (
  `id_extrasXls` INT(11) NOT NULL AUTO_INCREMENT,
  `id_empleado_reporta` BIGINT(20) NULL DEFAULT NULL,
  `mes_reporta` INT(11) NULL DEFAULT NULL,
  `archivo` TEXT NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  `id_destino` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_extrasXls`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`th_extrasXls`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`th_extrasXls` (
  `id_extrasXls` INT(11) NOT NULL AUTO_INCREMENT,
  `id_empleado_reporta` BIGINT(20) NULL DEFAULT NULL,
  `mes_reporta` INT(11) NULL DEFAULT NULL,
  `archivo` TEXT NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  `id_destino` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_extrasXls`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`th_novedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`th_novedades` (
  `id_novedad` INT(11) NOT NULL AUTO_INCREMENT,
  `id_contrato` INT(11) NULL DEFAULT NULL,
  `id_empleado_reporta` BIGINT(20) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `evidencia` TEXT NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `dias` DOUBLE NULL DEFAULT NULL,
  `cerrado` VARCHAR(2) NULL DEFAULT NULL,
  `archivo` TEXT NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  `tipo_novedad` VARCHAR(60) NULL DEFAULT NULL,
  `visto` INT(11) NOT NULL,
  PRIMARY KEY (`id_novedad`))
ENGINE = InnoDB
AUTO_INCREMENT = 1183
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`th_rodamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`th_rodamientos` (
  `id_rodamiento` INT(11) NOT NULL AUTO_INCREMENT,
  `id_contrato` INT(11) NULL DEFAULT NULL,
  `id_empleado_reporta` BIGINT(20) NULL DEFAULT NULL,
  `mes_reporte` INT(11) NULL DEFAULT NULL,
  `dias` INT(11) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_rodamiento`))
ENGINE = InnoDB
AUTO_INCREMENT = 127
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`alm_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`alm_tipo` (
  `id_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `id_categoria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`tipos_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`tipos_usuario` (
  `id_tipos_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tipos` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipos_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`unidades_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`unidades_medida` (
  `id_unidad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL DEFAULT NULL,
  `requiere_ancho` INT(2) NULL DEFAULT NULL,
  `simbolo` TEXT NULL DEFAULT NULL,
  `requiere_medida` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = MyISAM
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`usuario_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`usuario_cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NULL DEFAULT NULL,
  `codigo_cliente` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`usuarios` (
  `id_usuario` INT(11) NOT NULL,
  `nombres_usuario` VARCHAR(50) NOT NULL,
  `apellidos_usuario` VARCHAR(50) NOT NULL,
  `user_usuario` VARCHAR(50) NOT NULL,
  `pass_usuario` VARCHAR(50) NOT NULL,
  `id_estado` INT(11) NOT NULL,
  `id_tipo_usuario` INT(11) NULL DEFAULT NULL,
  `correo_usuario` VARCHAR(45) NOT NULL,
  `id_dependencia` INT(11) NULL DEFAULT NULL,
  `is_app` INT(11) NOT NULL DEFAULT '0',
  `clave_app` VARCHAR(100) NULL DEFAULT NULL,
  `pass_app` INT NULL,
  `id_cargo` INT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`th_tiponovedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`th_tiponovedad` (
  `id_tipoNovedad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_novedad` VARCHAR(70) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `nombre_novedadAPP` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `fechas` INT(11) NULL DEFAULT NULL,
  `archivo_obligatorio` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoNovedad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`th_tipoNovedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`th_tipoNovedad` (
  `id_tipoNovedad` INT NOT NULL AUTO_INCREMENT,
  `nombre_novedad` VARCHAR(70) NULL,
  `nombre_novedadAPP` VARCHAR(45) NULL,
  `fechas` INT NULL,
  `archivo_obligatorio` INT NULL,
  PRIMARY KEY (`id_tipoNovedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`th_reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`th_reportes` (
  `idreportesTH` INT NOT NULL AUTO_INCREMENT,
  `id_destino` INT NULL,
  `id_usuario` INT NULL,
  `tipoReporte` INT NULL,
  PRIMARY KEY (`idreportesTH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`hseq_asistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`hseq_asistencia` (
  `id_asistencia` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario_reporta` INT(11) NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  `total_asistencia` INT(11) NULL DEFAULT NULL,
  `id_centro` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asistencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`hseq_detasistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`hseq_detasistencia` (
  `id_detalle` INT(11) NOT NULL AUTO_INCREMENT,
  `id_asistencia` INT(11) NULL DEFAULT NULL,
  `id_empleado` INT(11) NULL DEFAULT NULL,
  `horas_inasistencia` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`hseq_diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`hseq_diario` (
  `id_diario` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario_reporta` INT(11) NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  `id_centro` INT(11) NULL DEFAULT NULL,
  `n_accidentes_inc` INT(11) NULL DEFAULT NULL,
  `n_dias_inc` INT(11) NULL DEFAULT NULL,
  `n_accidentes_noinc` INT(11) NULL DEFAULT NULL,
  `n_accidentes_dia` INT(11) NULL DEFAULT NULL,
  `n_enfermedades` INT(11) NULL DEFAULT NULL,
  `n_diasenfermedad` INT(11) NULL DEFAULT NULL,
  `n_vehiculosUsados` INT(11) NULL DEFAULT NULL,
  `n_vehiculosUlivianos` INT(11) NULL DEFAULT NULL,
  `n_vehiculosUpesados` INT(11) NULL DEFAULT NULL,
  `n_accidentesVehiculos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_diario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`hseq_semana`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`hseq_semana` (
  `id_semana` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario_reporta` INT(11) NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  `id_centro` INT(11) NULL DEFAULT NULL,
  `n_inspecciones` INT(11) NULL DEFAULT NULL,
  `n_charlas` INT(11) NULL DEFAULT NULL,
  `n_capacitaciones` INT(11) NULL DEFAULT NULL,
  `n_ats` INT(11) NULL DEFAULT NULL,
  `n_permisosAltura` INT(11) NULL DEFAULT NULL,
  `n_entregaEPP` INT(11) NULL DEFAULT NULL,
  `n_retiros` INT(11) NULL DEFAULT NULL,
  `n_pazysalvosRetiros` INT(11) NULL DEFAULT NULL,
  `n_nuevos` INT(11) NULL DEFAULT NULL,
  `n_gasVehiculos` DOUBLE NULL DEFAULT NULL,
  `n_dieselVehiculos` DOUBLE NULL DEFAULT NULL,
  `n_gasEquipos` DOUBLE NULL DEFAULT NULL,
  `n_dieselEquipos` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id_semana`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`hseq_tipoactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`hseq_tipoactividad` (
  `id_tipoActividad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreActividad` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipoActividad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`hseq_programacionactividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`hseq_programacionactividades` (
  `id_programacion` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario_programa` INT(11) NULL DEFAULT NULL,
  `fecha_programa` DATE NULL DEFAULT NULL,
  `id_tipoActividad` INT(11) NULL DEFAULT NULL,
  `id_centro` INT(11) NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  `duracion` DOUBLE NULL DEFAULT NULL,
  `evidencias` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `observaciones` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_programacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `ecoservi_plataforma17`.`hseq_reporteactividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecoservi_plataforma17`.`hseq_reporteactividades` (
  `id_reporte` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario_reporta` INT(11) NULL DEFAULT NULL,
  `fecha_reporte` DATE NULL DEFAULT NULL,
  `fecha_ejecucion` DATE NULL DEFAULT NULL,
  `id_programacion` INT(11) NULL DEFAULT NULL,
  `duracionReal` DOUBLE NULL DEFAULT NULL,
  `evaluacion` INT(11) NULL DEFAULT NULL,
  `evidencias` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `observaciones` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_reporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
